Sundsvallskommun/api-service-case-data

- src/integration-test/java/se/sundsvall/casedata/apptest/ErrandResourceIT.java
- src/main/java/se/sundsvall/casedata/api/AttachmentResource.java
- src/main/java/se/sundsvall/casedata/api/ErrandResource.java
Needed by frontend to POC a solution with relative location-header URL:s
> UF-7292: Change to relative URL:s

- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderService.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderServiceTest.java
Change messageID for messages created from email and add check to avoid duplicates.
> UF-7334: Add check for email save

- src/main/java/se/sundsvall/casedata/api/NotificationResource.java
- src/main/java/se/sundsvall/casedata/api/model/Notification.java
- src/main/java/se/sundsvall/casedata/api/model/PatchNotification.java
- src/main/java/se/sundsvall/casedata/api/model/PostNotification.java
- src/main/java/se/sundsvall/casedata/service/NoteService.java
- src/main/java/se/sundsvall/casedata/service/NotificationService.java
- src/main/java/se/sundsvall/casedata/service/util/Constants.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/api/NotificationResourceFailuresTest.java
- src/test/java/se/sundsvall/casedata/api/NotificationsResourceTest.java
- src/test/java/se/sundsvall/casedata/api/model/NotificationTest.java
- src/test/java/se/sundsvall/casedata/api/model/PatchNotificationTest.java
- src/test/java/se/sundsvall/casedata/api/model/PostNotificationTest.java
- src/test/java/se/sundsvall/casedata/service/NoteServiceTest.java
> UF-10373: Added API for notifications

- src/main/java/se/sundsvall/casedata/integration/db/ErrandRepository.java
- src/main/java/se/sundsvall/casedata/service/ErrandService.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorker.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionWorker.java
- src/main/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/main/resources/application-it.yml
- src/main/resources/application.yml
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorkerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionWorkerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
> UF-10398: Add scheduled job to clear out expired suspensions

- src/main/java/se/sundsvall/casedata/api/NotificationResource.java
- src/main/java/se/sundsvall/casedata/api/model/PatchNotification.java
- src/main/java/se/sundsvall/casedata/integration/db/NotificationRepository.java
- src/main/java/se/sundsvall/casedata/service/NotificationService.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/EntityMapper.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/PatchMapper.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/TestUtil.java
- src/test/java/se/sundsvall/casedata/api/model/PatchNotificationTest.java
- src/test/java/se/sundsvall/casedata/service/NotificationServiceTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/EntityMapperTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/PatchMapperTest.java
> UF-10375: Added notification-logic.

- pom.xml
- src/main/java/se/sundsvall/casedata/api/model/Notification.java
- src/main/java/se/sundsvall/casedata/api/model/PatchNotification.java
- src/main/java/se/sundsvall/casedata/integration/employee/EmployeeClient.java
- src/main/java/se/sundsvall/casedata/integration/employee/configuration/EmployeeConfiguration.java
- src/main/java/se/sundsvall/casedata/integration/employee/configuration/EmployeeProperties.java
- src/main/java/se/sundsvall/casedata/service/EmployeeService.java
- src/main/java/se/sundsvall/casedata/service/NotificationService.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/EntityMapper.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/PatchMapper.java
- src/main/resources/api/openapi.yaml
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/main/resources/application.yml
- src/main/resources/contract/employee.yml
- src/test/java/se/sundsvall/casedata/TestUtil.java
- src/test/java/se/sundsvall/casedata/api/NotificationResourceFailuresTest.java
- src/test/java/se/sundsvall/casedata/api/model/PatchNotificationTest.java
- src/test/java/se/sundsvall/casedata/integration/employee/configuration/EmployeeConfigurationTest.java
- src/test/java/se/sundsvall/casedata/integration/employee/configuration/EmployeePropertiesTest.java
- src/test/java/se/sundsvall/casedata/service/EmployeeServiceTest.java
- src/test/java/se/sundsvall/casedata/service/NotificationServiceTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/EntityMapperTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/PatchMapperTest.java
> UF-10464: Added employee integration

- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionWorker.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionWorkerTest.java
> UF-10477: Adjust scheduled job for suspensions

- pom.xml
- src/main/java/se/sundsvall/casedata/integration/db/listeners/AppealListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/ErrandListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/NotificationListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/StakeholderListener.java
- src/main/java/se/sundsvall/casedata/integration/webmessagecollector/configuration/WebMessageCollectorConfiguration.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationWorker.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorScheduler.java
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/main/resources/application.yml
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationWorkerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionSchedulerTest.java
> UF-10389: Added scheduled notification cleanup job.

- src/main/java/se/sundsvall/casedata/service/scheduler/MessageMapper.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorker.java
- src/main/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/EntityMapper.java
- src/main/resources/db/migration/V2_7__populate_old_data_with_namespace.sql
- src/test/java/se/sundsvall/casedata/service/scheduler/MessageMapperTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorkerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
- UF-10287: Part 2: Update additional tables with namespace
- UF-10288: Update emailreader integration so namespace is populated
- UF-10289: Update WebMessageCollector integation so namespace is populated
- also fixes some other places municipalityId or namespace werent populated properly.
> Solves the following: UF-10287, UF-10288, UF-10289

- src/main/java/se/sundsvall/casedata/service/util/mappers/EntityMapper.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/EntityMapperTest.java
> UF-10730: NPE handling for saving with empty lists

- src/main/resources/db/migration/V2_8__correct_namespace_naming.sql
> UF-10771: Update namespace name

- src/main/java/se/sundsvall/casedata/api/model/Errand.java
- src/main/java/se/sundsvall/casedata/api/model/Notification.java
- src/main/java/se/sundsvall/casedata/api/model/PatchErrand.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/api/model/ErrandTest.java
- src/test/java/se/sundsvall/casedata/api/model/PatchErrandTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/EntityMapperTest.java
> UF-10734: Added API-modifications

- src/integration-test/resources/HistoryIT/__files/test01_getErrandHistory/response.json
- src/integration-test/resources/HistoryIT/__files/test02_getAttachmentHistory/response.json
- src/integration-test/resources/HistoryIT/__files/test03_getDecisionHistory/response.json
- src/integration-test/resources/HistoryIT/__files/test04_getFacilitiesHistory/response.json
- src/integration-test/resources/HistoryIT/__files/test05_getNotesHistory/response.json
- src/integration-test/resources/HistoryIT/__files/test06_getStakeholdersHistory/response.json
- src/main/java/se/sundsvall/casedata/api/HistoryResource.java
- src/main/java/se/sundsvall/casedata/api/model/history/ElementChangesItem.java
- src/main/java/se/sundsvall/casedata/api/model/history/History.java
- src/main/java/se/sundsvall/casedata/service/HistoryService.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/api/HistoryResourceTest.java
- src/test/java/se/sundsvall/casedata/service/HistoryServiceTest.java
> UF-10725: Make history resource return object instead of String

- src/integration-test/java/se/sundsvall/casedata/apptest/ErrandIT.java
- src/integration-test/resources/ErrandListenerIT/__files/test02_updateErrand/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test02_updateErrand/request.json
- src/integration-test/resources/db/scripts/errandIT-testdata.sql
- src/integration-test/resources/db/scripts/truncate.sql
- src/main/java/se/sundsvall/casedata/api/model/validation/impl/UniqueDecisionTypeValidator.java
- src/main/java/se/sundsvall/casedata/integration/db/NotificationRepository.java
- src/main/java/se/sundsvall/casedata/service/DecisionService.java
- src/main/java/se/sundsvall/casedata/service/HistoryService.java
- src/test/resources/db/scripts/truncate.sql
> UF-10737: Added/updated IT-tests

- src/main/java/se/sundsvall/casedata/api/AttachmentResource.java
- src/main/java/se/sundsvall/casedata/api/DecisionResource.java
- src/main/java/se/sundsvall/casedata/api/ErrandResource.java
- src/main/java/se/sundsvall/casedata/api/FacilityResource.java
- src/main/java/se/sundsvall/casedata/api/HistoryResource.java
- src/main/java/se/sundsvall/casedata/api/MessageAttachmentResource.java
- src/main/java/se/sundsvall/casedata/api/MessageResource.java
- src/main/java/se/sundsvall/casedata/api/NoteResource.java
- src/main/java/se/sundsvall/casedata/api/NotificationResource.java
- src/main/java/se/sundsvall/casedata/api/ParkingPermitResource.java
- src/main/java/se/sundsvall/casedata/api/StakeholderResource.java
- src/main/java/se/sundsvall/casedata/api/StatusResource.java
- src/main/resources/api/openapi.yaml
> UF-10836: Removed incorrect content type.

- pom.xml
- src/main/java/se/sundsvall/casedata/integration/landandexploitation/LandAndExploitationClient.java
- src/main/java/se/sundsvall/casedata/integration/landandexploitation/LandAndExploitationIntegration.java
- src/main/java/se/sundsvall/casedata/service/ErrandService.java
- src/main/java/se/sundsvall/casedata/service/NotificationService.java
- src/main/java/se/sundsvall/casedata/service/ProcessService.java
- src/main/resources/contract/pw-land-and-exploitation.yml
- src/test/java/se/sundsvall/casedata/integration/landandexploitation/LandAndExploitationIntegrationTest.java
- src/test/java/se/sundsvall/casedata/service/ErrandServiceTest.java
- src/test/java/se/sundsvall/casedata/service/ProcessServiceTest.java
> UF-10870: Update version of Land-and-exploitation integration

- src/main/java/se/sundsvall/casedata/service/util/mappers/PatchMapper.java
> UF-10883: ExtraParameters should not be emptied if not present in patch object

- src/integration-test/java/se/sundsvall/casedata/apptest/ErrandIT.java
- src/integration-test/resources/ErrandListenerIT/__files/test01_persistErrandUnknown/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test02_updateErrand/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test03_generateErrandNumberForParkingPermit/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test04_generateErrandNumberForLostParkingPermit/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test06_generateErrandNumberForMEX/expected.json
- src/main/java/se/sundsvall/casedata/integration/db/listeners/AppealListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/DecisionListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/ErrandListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/ExtraParameterListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/FacilityListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/NoteListener.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/StakeholderListener.java
> DRAKEN-686: Change errandListener to PreUpdate

- src/main/java/se/sundsvall/casedata/service/ErrandService.java
- src/main/resources/application.yml
> UF-10881: Prevent circutbreaker to trigger on faulty input

- src/main/java/se/sundsvall/casedata/service/MessageService.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorker.java
- src/main/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/EntityMapper.java
- src/test/java/se/sundsvall/casedata/service/MessageServiceTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorkerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/EntityMapperTest.java
> UF-11082: Messages should create notifications

- src/main/resources/db/migration/V3_5__extend_column_with_in_extra_parameter_values.sql
> UF-11086: Add script for column width extension

- src/main/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorker.java
- src/test/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/webmessagecollector/WebMessageCollectorWorkerTest.java
> UF-11239: Fix

- src/main/java/se/sundsvall/casedata/integration/emailreader/EmailReaderClient.java
- src/main/java/se/sundsvall/casedata/integration/employee/EmployeeClient.java
- src/main/java/se/sundsvall/casedata/integration/landandexploitation/LandAndExploitationClient.java
- src/main/java/se/sundsvall/casedata/integration/parkingpermit/ParkingPermitClient.java
- src/main/java/se/sundsvall/casedata/integration/webmessagecollector/WebMessageCollectorClient.java
> UF-11345: Add circuitbreaker-annotation

- src/main/java/se/sundsvall/casedata/api/model/validation/enums/AttachmentCategory.java
> UF-11405: Add attachment categories

- src/integration-test/resources/ErrandListenerIT/__files/test01_persistErrandUnknown/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test03_generateErrandNumberForParkingPermit/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test04_generateErrandNumberForLostParkingPermit/expected.json
- src/integration-test/resources/ErrandListenerIT/__files/test06_generateErrandNumberForMEX/expected.json
- src/main/java/se/sundsvall/casedata/integration/db/model/ErrandEntity.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorker.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorkerTest.java
For the record. This is deployed and confirmed working. As this was kinda urgent and I'm the only one holding down the fort today.
> UF-11404: Move transactional and do delete only if successful

- src/main/java/se/sundsvall/casedata/integration/db/model/ErrandEntity.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapper.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorker.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderMapperTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorkerTest.java
> Merge main to 10

- src/integration-test/java/se/sundsvall/casedata/apptest/ErrandIT.java
- src/integration-test/java/se/sundsvall/casedata/apptest/ErrandListenerIT.java
- src/integration-test/java/se/sundsvall/casedata/apptest/RollbackIT.java
- src/integration-test/resources/ErrandListenerIT/__files/test01_persistErrandUnknown/response.json
- src/integration-test/resources/ErrandListenerIT/__files/test03_generateErrandNumberForParkingPermit/response.json
- src/integration-test/resources/ErrandListenerIT/__files/test04_generateErrandNumberForLostParkingPermit/response.json
- src/main/java/se/sundsvall/casedata/api/model/validation/enums/Shortcode.java
- src/test/java/se/sundsvall/casedata/integration/db/ErrandRepositoryTest.java
> UF-11671: Changed namespace of ParkingPermit in Shortcode

- src/main/java/se/sundsvall/casedata/api/model/PatchNotification.java
- src/main/resources/api/openapi.yaml
> UF-14196: Remove readonly for errandId on patchNotification object

- src/main/java/se/sundsvall/casedata/api/model/validation/enums/StakeholderRole.java
- src/main/java/se/sundsvall/casedata/api/model/validation/impl/ValidStakeholderRoleConstraintValidator.java
- src/test/java/se/sundsvall/casedata/api/model/validation/enums/StakeholderRoleTest.java
> UF-14190: Add new stakeholder roles and UF-14199: Remove deprecated role

- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorker.java
- src/test/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorkerTest.java
> UF-14305: Fix NPE in emailreaderworker

- src/main/java/se/sundsvall/casedata/integration/db/model/ErrandEntity.java
- src/main/resources/db/migration/V3_8__add_status_field_on_errand.sql
- src/test/java/se/sundsvall/casedata/integration/db/model/ErrandEntityTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/EntityMapperTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/PatchMapperTest.java
- src/test/resources/db/schema.sql
> UF-14319: Add new status field on errand entity

- src/main/java/se/sundsvall/casedata/api/model/Errand.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/api/model/ErrandTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/EntityMapperTest.java
> UF-14320: Add new status field on errand

- src/integration-test/resources/db/scripts/notificationIT-testdata.sql
- src/main/java/se/sundsvall/casedata/integration/db/model/NotificationEntity.java
- src/main/resources/db/migration/V3_8__add_column_to_notification_table.sql
- src/test/java/se/sundsvall/casedata/integration/db/listeners/NotificationListenerTest.java
- src/test/java/se/sundsvall/casedata/integration/db/model/NotificationEntityTest.java
- src/test/resources/db/schema.sql
> UF-14208: Added globalAcknowledged in persistence layer

- src/main/java/se/sundsvall/casedata/integration/db/model/NotificationEntity.java
- src/main/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationWorker.java
- src/test/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationSchedulerSchedlockTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationSchedulerTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationWorkerTest.java
> UF-14210: Refactoring of scheduled notification cleanup job.

- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionWorker.java
> UF-14470: Fix suspension worker bug.

- src/main/java/se/sundsvall/casedata/service/StatusService.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/notifications/NotificationScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionScheduler.java
- src/main/java/se/sundsvall/casedata/service/scheduler/supensions/SuspensionWorker.java
> Main to 11.0

- changelog.md
> UF-14529: Update changelog for 11.0

- src/main/resources/db/migration/V3_8__add_status_field_on_errand.sql
> UF-14590: Backport DB-script

- src/main/java/se/sundsvall/casedata/api/model/validation/enums/Shortcode.java
> UF-14553: Add new shortcode for ANGE_PARKING_PERMIT

- src/integration-test/resources/ErrandIT/mappings/getEmployeePersonalData.json
- src/integration-test/resources/NotificationIT/__files/test03_createNotification/mappings/getCreatorEmployeePersonalData.json
- src/integration-test/resources/NotificationIT/__files/test03_createNotification/mappings/getOwnerEmployeePersonalData.json
- src/integration-test/resources/NotificationIT/__files/test04_updateNotification/mappings/getOwnerEmployeePersonalData.json
- src/main/java/se/sundsvall/casedata/integration/employee/EmployeeClient.java
- src/main/java/se/sundsvall/casedata/service/EmployeeService.java
- src/main/java/se/sundsvall/casedata/service/NotificationService.java
- src/main/resources/contract/employee.yml
- src/test/java/se/sundsvall/casedata/service/EmployeeServiceTest.java
- src/test/java/se/sundsvall/casedata/service/NotificationServiceTest.java
> UF-14668: Lifted Employee API version

- src/main/resources/db/migration/V3_11__populate_errand_status_from_errand_statuses.sql
> UF-14321: Flwayscript to populate errand.status with errand.statuses values

- src/integration-test/java/se/sundsvall/casedata/apptest/AttachmentIT.java
- src/integration-test/resources/AttachmentIT/__files/test03_putAttachment/mappings/getOwnerEmployeePersonalData.json
- src/integration-test/resources/AttachmentIT/__files/test03_putAttachment/mappings/postToken.json
- src/integration-test/resources/AttachmentIT/__files/test05_deleteAttachmentOnErrand/mappings/getEmployeePersonalData.json
- src/integration-test/resources/AttachmentIT/__files/test05_deleteAttachmentOnErrand/mappings/postToken.json
- src/integration-test/resources/AttachmentIT/__files/test07_createAttachment/mappings/getEmployeePersonalData.json
- src/integration-test/resources/AttachmentIT/__files/test07_createAttachment/mappings/postToken.json
- src/integration-test/resources/AttachmentIT/__files/test10_patchAttachment/mappings/getEmployeePersonalData.json
- src/integration-test/resources/AttachmentIT/__files/test10_patchAttachment/mappings/postToken.json
- src/integration-test/resources/db/scripts/attachmentIT-testdata.sql
- src/main/java/se/sundsvall/casedata/service/AttachmentService.java
- src/main/java/se/sundsvall/casedata/service/util/Constants.java
- src/test/java/se/sundsvall/casedata/service/AttachmentServiceTest.java
> UF-14708: Attachment CRUD should generate notifications

- pom.xml
- src/main/java/se/sundsvall/casedata/api/model/MessageRequest.java
- src/main/java/se/sundsvall/casedata/api/model/MessageResponse.java
- src/main/java/se/sundsvall/casedata/api/model/validation/enums/MessageType.java
- src/main/java/se/sundsvall/casedata/integration/db/model/MessageEntity.java
- src/main/java/se/sundsvall/casedata/service/scheduler/MessageMapper.java
- src/main/resources/api/openapi.yaml
- src/main/resources/db/migration/V3_9__add_internal_field_on_message.sql
- src/test/java/se/sundsvall/casedata/api/model/MessageRequestTest.java
- src/test/java/se/sundsvall/casedata/api/model/MessageResponseTest.java
- src/test/java/se/sundsvall/casedata/integration/db/MessageRepositoryTest.java
- src/test/java/se/sundsvall/casedata/integration/db/model/MessageEntityTest.java
- src/test/resources/db/schema.sql
> UF-14772: Added internal to message and added message type MYPAGES

- src/main/java/se/sundsvall/casedata/api/MessageResource.java
- src/main/java/se/sundsvall/casedata/api/model/MessageResponse.java
- src/main/java/se/sundsvall/casedata/integration/db/MessageRepository.java
- src/main/java/se/sundsvall/casedata/service/MessageService.java
- src/main/java/se/sundsvall/casedata/service/scheduler/MessageMapper.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/api/MessageResourceTest.java
- src/test/java/se/sundsvall/casedata/api/model/MessageResponseTest.java
- src/test/java/se/sundsvall/casedata/integration/db/MessageRepositoryTest.java
- src/test/java/se/sundsvall/casedata/service/MessageServiceTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/MessageMapperTest.java
- src/test/resources/db/scripts/testdata-junit.sql
> UF-14773: Added new resource for external messages

- src/main/java/se/sundsvall/casedata/service/MessageService.java
- src/main/java/se/sundsvall/casedata/service/scheduler/emailreader/EmailReaderWorker.java
- src/test/java/se/sundsvall/casedata/service/MessageServiceTest.java
> UF-14898: Changed notification texts

- src/main/java/se/sundsvall/casedata/integration/db/model/NotificationEntity.java
- src/main/resources/db/migration/V3_12__add_subtype_to_notification.sql
- src/test/java/se/sundsvall/casedata/integration/db/model/NotificationEntityTest.java
- src/test/resources/db/schema.sql
> UF-15207: Add subtype to notification entity

- src/main/java/se/sundsvall/casedata/integration/db/model/StatusEntity.java
- src/main/resources/db/migration/V3_13__rename_status_datetime_to_created.sql
- src/test/resources/db/schema.sql
- src/test/resources/db/scripts/testdata-junit.sql
> UF-14476: Rename date_time to created for statuses

- src/main/java/se/sundsvall/casedata/api/model/validation/enums/AttachmentCategory.java
> UF-15403: add attachment category

- src/main/java/se/sundsvall/casedata/api/model/validation/enums/StakeholderRole.java
- src/test/java/se/sundsvall/casedata/api/model/validation/enums/StakeholderRoleTest.java
> DRAKEN-1308: add stakeholder role

- src/main/resources/db/migration/V1__initial_schema.sql
> UF-15647: Added javers tables

- src/main/java/se/sundsvall/casedata/api/AttachmentResource.java
- src/main/java/se/sundsvall/casedata/integration/db/model/ErrandEntity.java
- src/main/resources/api/openapi.yaml
- src/main/resources/db/migration/V1_1__errand_number_should_be_unique_per_municipality_id.sql
- src/test/resources/db/schema.sql
> UF-16040: Errand_number should be unique per municipalityId

- src/main/java/se/sundsvall/casedata/integration/db/ConversationRepository.java
- src/main/java/se/sundsvall/casedata/integration/db/model/ConversationEntity.java
- src/main/resources/db/migration/V1_2__add_conversation_table.sql
- src/test/java/se/sundsvall/casedata/integration/db/ConversationRepositoryTest.java
- src/test/java/se/sundsvall/casedata/integration/db/model/ConversationEntityTest.java
- src/test/resources/db/schema.sql
- src/test/resources/db/scripts/testdata-junit.sql
- src/test/resources/db/scripts/truncate.sql
> UF-16224: Add db conversation (entity, flyway, repository)

- changelog/changelog-11.2.md
- src/main/java/se/sundsvall/casedata/api/ConversationResource.java
- src/main/resources/api/openapi.yaml
> UF-16289: Correct tag for new resources

- README.md
- pom.xml
- src/main/java/se/sundsvall/casedata/integration/messaging/MessagingClient.java
- src/main/java/se/sundsvall/casedata/integration/messaging/configuration/MessagingConfiguration.java
- src/main/java/se/sundsvall/casedata/integration/messaging/configuration/MessagingProperties.java
- src/main/resources/application-it.yml
- src/main/resources/application-junit.yml
- src/main/resources/application.yml
- src/main/resources/contract/messaging-api.yaml
- src/test/java/se/sundsvall/casedata/integration/messaging/configuration/MessagingConfigurationTest.java
- src/test/java/se/sundsvall/casedata/integration/messaging/configuration/MessagingPropertiesTest.java
> UF-16465: Add messaging integration

- src/main/java/se/sundsvall/casedata/integration/relation/RelationClient.java
- src/main/java/se/sundsvall/casedata/integration/relation/configuration/RelationConfiguration.java
- src/main/resources/application.yml
> UF-16586: Bypass 404 for relation integration

- src/main/java/se/sundsvall/casedata/service/util/mappers/ConversationMapper.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/ConversationMapperTest.java
> UF-16587: Fix mapper bug for conversation

- src/main/java/se/sundsvall/casedata/integration/db/ErrandRepository.java
- src/main/java/se/sundsvall/casedata/integration/db/listeners/ErrandListener.java
> UF-16599: optimize and read one errand instead of all errands when generating errandNumber

- src/main/java/se/sundsvall/casedata/service/ConversationService.java
> UF-16607: Dont throw errors if messaging notification was not possible to send

- src/main/java/se/sundsvall/casedata/integration/messageexchange/MessageExchangeClient.java
- src/main/java/se/sundsvall/casedata/service/ConversationService.java
- src/main/java/se/sundsvall/casedata/service/MessageExchangeSyncService.java
- src/main/java/se/sundsvall/casedata/service/scheduler/messageexchange/MessageExchangeWorker.java
- src/main/java/se/sundsvall/casedata/service/util/ConversationEvent.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/ConversationMapper.java
- src/test/java/se/sundsvall/casedata/service/ConversationServiceTest.java
- src/test/java/se/sundsvall/casedata/service/MessageExchangeSyncServiceTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/messageexchange/MessageExchangeWorkerTest.java
- src/test/java/se/sundsvall/casedata/service/util/ConversationEventTest.java
- src/test/java/se/sundsvall/casedata/service/util/mappers/ConversationMapperTest.java
> UF-16571: sync attachments to errand

- pom.xml
- src/main/java/se/sundsvall/casedata/service/MessageExchangeSyncService.java
- src/main/java/se/sundsvall/casedata/service/NotificationService.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/ConversationMapper.java
- src/main/java/se/sundsvall/casedata/service/util/mappers/EntityMapper.java
> UF-16712: Fix log injection vulnerability + other issues

- src/integration-test/resources/ConversationIT/__files/test01_getConversation/response/message-exchange-getConversations.json
- src/integration-test/resources/ConversationIT/__files/test04_createConversation/response.json
- src/integration-test/resources/ConversationIT/__files/test04_createConversation/response/message-exchange-getConversations.json
- src/main/java/se/sundsvall/casedata/service/ConversationService.java
- src/main/java/se/sundsvall/casedata/service/MessageExchangeSyncService.java
- src/main/java/se/sundsvall/casedata/service/scheduler/messageexchange/MessageExchangeScheduler.java
- src/test/java/se/sundsvall/casedata/service/ConversationServiceTest.java
- src/test/java/se/sundsvall/casedata/service/MessageExchangeSyncServiceTest.java
- src/test/java/se/sundsvall/casedata/service/scheduler/messageexchange/MessageExchangeSchedulerTest.java
> UF-16411: Refactor message-exchange sync and add notifications

- src/main/java/se/sundsvall/casedata/integration/messaging/MessagingMapper.java
- src/test/java/se/sundsvall/casedata/integration/messaging/MessagingMapperTest.java
> UF-16740: Fixed missing emailName for messaging

- src/main/java/se/sundsvall/casedata/service/MessageService.java
- src/test/java/se/sundsvall/casedata/service/MessageServiceTest.java
> MSI-283: dont send messsagenotification if client sent message

- src/main/java/se/sundsvall/casedata/api/model/validation/enums/AttachmentCategory.java
> UF-16966: add attachmentCategories

- src/main/java/se/sundsvall/casedata/integration/db/CaseTypeRepository.java
- src/main/java/se/sundsvall/casedata/integration/db/model/CaseTypeEntity.java
- src/main/resources/db/migration/V1_6__add_casetype_table.sql
- src/test/java/se/sundsvall/casedata/integration/db/CaseTypeRepositoryTest.java
- src/test/java/se/sundsvall/casedata/integration/db/model/CaseTypeEntityTest.java
- src/test/resources/db/schema.sql
- src/test/resources/db/scripts/testdata-junit.sql
> UF-17176: Create casetype entity

- pom.xml
- src/main/java/se/sundsvall/casedata/api/MetadataCaseTypeResource.java
- src/main/java/se/sundsvall/casedata/api/model/CaseType.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/api/MetadataCaseTypeResourceTest.java
- src/test/java/se/sundsvall/casedata/api/model/CaseTypeTest.java
> UF-17175: Create casetype api resources

- src/main/resources/application.yml
> UF-17221: set correct default mex namespace

- src/integration-test/resources/DecisionIT/__files/test03_putDecision/request.json
- src/integration-test/resources/DecisionIT/__files/test03_putDecision/response.json
- src/integration-test/resources/MessageIT/__files/test01_getMessages/response.json
- src/integration-test/resources/MessageIT/__files/test02_getMessage/response.json
- src/integration-test/resources/MessageIT/__files/test03_createMessage/request.json
- src/integration-test/resources/MessageIT/__files/test03_createMessage/response.json
- src/integration-test/resources/MessageIT/__files/test07_getExternalMessages/response.json
- src/integration-test/resources/db/scripts/messageIT-testdata.sql
- src/main/java/se/sundsvall/casedata/api/model/MessageRequest.java
- src/main/java/se/sundsvall/casedata/api/model/MessageResponse.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casedata/api/model/MessageRequestTest.java
- src/test/resources/db/scripts/testdata-junit.sql
> UF-17393: Change to a fake phone number in test/doc
